### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by chenyu1990** [bububa/WeWorkFinanceSDK#1]
`/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:37:8: cannot use ptr (variable of type *_Ctype_struct_WeWorkFinanceSdk_t) as type _Ctype_struct_WeWorkFinanceSdk_t in struct literal
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:43:70: cannot use _cgo0 (variable of type _Ctype_struct_WeWorkFinanceSdk_t) as type *_Ctype_struct_WeWorkFinanceSdk_t in argument to _Cfunc_DestroySdk
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:66:97: cannot use _cgo0 (variable of type _Ctype_struct_WeWorkFinanceSdk_t) as type *_Ctype_struct_WeWorkFinanceSdk_t in argument to _Cfunc_GetChatData
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:94:24: cannot use encryptKey (variable of type string) as type *_Ctype_char in variable declaration
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:94:36: cannot use encryptMsg (variable of type string) as type *_Ctype_char in variable declaration
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:191:88: cannot use _cgo0 (variable of type _Ctype_struct_WeWorkFinanceSdk_t) as type *_Ctype_struct_WeWorkFinanceSdk_t in argument to _Cfunc_GetMediaData
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:198:49: cannot use int(func() _Ctype_int {…}()) (value of type int) as type _Ctype_int in variable declaration
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:198:71: cannot use _cgo0 (variable of type *_Ctype_char) as type unsafe.Pointer in argument to _Cfunc_GoBytes
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:222:49: cannot use int(func() _Ctype_int {…}()) (value of type int) as type _Ctype_int in variable declaration
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:222:72: cannot use _cgo0 (variable of type *_Ctype_char) as type unsafe.Pointer in argument to _Cfunc_GoBytes
/root/go/pkg/mod/github.com/bububa/!we!work!finance!s!d!k@v1.0.1/client.go:222:72: too many errors`

docker ubuntu 20.04

**Comment by chenyu1990** [comment]
go version go1.18 linux/amd64

**Comment by chenyu1990** [comment]
把所有报错都更正了后，`.NewClient` 返回的 err = `0:sdk failed`
已确认 secret 正确

**Comment by chenyu1990** [comment]
> 把所有报错都更正了后，`.NewClient` 返回的 err = `0:sdk failed` 已确认 secret 正确

返回判断的问题，非0才有错误，0为正常

更改后继续报错
`err:invalid character '\u009c' after top-level valueinvalid character '\u009c' after top-level value`

**Comment by bububa** [comment]
是调用GetChatData接口错误吗？

**Comment by bububa** [comment]
试试 v1.1.0
